#!/bin/bash

echo "1. Nano editor
2. vi editor
3. Links browser
4. Exit"

read key

if [ $key = "1" ]
then nano
elif [ $key = "2" ]
then vi
elif [ $key = "3" ]
then links
elif [ $key = "4" ]
then echo "Exited."
else
echo "Invalid Choice!"
fi
